"""initial schema

Revision ID: 3db4d63d21e4
Revises:
Create Date: 2026-04-23 11:07:51.007515

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3db4d63d21e4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'favorites',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_hash', sa.String(length=64), nullable=False),
        sa.Column('guild_hash', sa.String(length=64), nullable=False),
        sa.Column('instant_id', sa.String(length=128), nullable=False),
        sa.Column('instant_name', sa.String(length=255), nullable=False),
        sa.Column('page_url', sa.String(length=512), nullable=True),
        sa.Column('mp3_url', sa.String(length=512), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'user_hash',
            'guild_hash',
            'instant_id',
            name='uq_fav_user_guild_instant',
        ),
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(
            'ix_fav_user_guild', ['user_hash', 'guild_hash'], unique=False
        )

    op.create_table(
        'guild_settings',
        sa.Column('guild_hash', sa.String(length=64), nullable=False),
        sa.Column('idle_timeout_seconds', sa.Integer(), nullable=True),
        sa.Column('skip_vote_threshold', sa.Integer(), nullable=True),
        sa.Column('default_volume_pct', sa.Integer(), nullable=True),
        sa.Column('locale', sa.String(length=8), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('guild_hash'),
    )
    op.create_table(
        'play_history',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_hash', sa.String(length=64), nullable=False),
        sa.Column('guild_hash', sa.String(length=64), nullable=False),
        sa.Column('instant_id', sa.String(length=128), nullable=False),
        sa.Column('instant_name', sa.String(length=255), nullable=False),
        sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('play_history', schema=None) as batch_op:
        batch_op.create_index(
            'ix_play_guild_at', ['guild_hash', 'played_at'], unique=False
        )
        batch_op.create_index('ix_play_instant', ['instant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play_history', schema=None) as batch_op:
        batch_op.drop_index('ix_play_instant')
        batch_op.drop_index('ix_play_guild_at')

    op.drop_table('play_history')
    op.drop_table('guild_settings')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index('ix_fav_user_guild')

    op.drop_table('favorites')
    # ### end Alembic commands ###
