name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          MYINSTANTS_BOT_TOKEN: ${{ secrets.MYINSTANTS_BOT_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/my-instants-discord-bot
            git pull
            export MYINSTANTS_BOT_TOKEN=
            docker-compose -f compose.yml build
            docker-compose -f compose.yml up -d
